name: 'My Action'
description: 'My first actions with docker'
inputs:
 FIRST_NAME:
   description: 'The first name'
   required: false
   default: 'JUAN'
outputs:
 time:
   description: 'The elapsed time'
runs:
 using: 'docker'
 image: 'Dockerfile'
 args:
   - ${{ inputs.FIRST_NAME }}
